name: tumi_nol
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  get_it: ^8.0.3
  shadcn_ui: ^0.23.3
  gap: ^3.0.1
  fpdart: ^1.1.1
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  youtube_explode_dart: ^2.3.10
  youtube_player_flutter: ^9.1.1
  riverpod_annotation: ^2.6.1
  timeago: ^3.7.0
  file_picker: ^9.2.3
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  path: ^1.9.1
  file_selector: ^1.0.3
  super_sliver_list: ^0.4.1
  draggable_menu: ^4.4.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2

dependency_overrides:
  freezed_annotation: ^2.2.0

flutter:
  uses-material-design: true
